### ISSUE TITLE
plan to move to official repo

### ISSUE THREAD

**Issue by guolinke** [Allardvm/LightGBM.jl#13]
Thanks for great work!
Do you have plan to make this as a official package ?

**Comment by Allardvm** [comment]
You're welcome!

I'm all for turning this into an official package and wouldn't mind contributing to make this happen. As far as I can see, there are three topic we'll need to consider before doing so:

1. I would prefer to keep this as a separate repo. The reason is that Julia libraries typically reside in a separate git, so they can be registered as a Julia packages (see: http://docs.julialang.org/en/stable/manual/packages/#package-development), which allows them to be installed simply with `Pkg.add("LightGBM")`—which is what Julia users will expect. Of course, I'd be happy to grant the LightGBM team full access to this repo. We can also add a direct link to this repo in the LightGBM repo.
2. This package's interface differs from the R and Python interface. In general, it's a bit more high-level—but quite similar to Scikit. Are you ok with that, or would you rather see a similar interface? I'm happy to swap things around a bit.
3. The package doesn't support all LightGBM features yet. Most notably, there's no support for LambdaRank estimators. I'd say we would have to add that before marking this as an official repo.

Feel free to add points, if you have any concerns/remarks.

**Comment by guolinke** [comment]
@Allardvm sure, I think keep it as a separate repo is OK. I will add a link to this repo.
For the interfaces design, I think it is up to you. For R/Python 's interfaces, actually it is kind of complicate..
For other features, It is not so urgent, just take your time. 

Thanks again !

**Comment by Allardvm** [comment]
Closing this in favour of the new (and maintained) repository located here: https://github.com/IQVIA-ML/LightGBM.jl .
